project:
  type: website

website:
  title: "Sjochengberg Recipes"
  navbar:
    right:
      - icon: github
        href: https://github.com/ddsjoberg/recipes
format:
  html:
    theme: 
      - yeti
      - styles.scss

editor: visual

